language: go
go:
- '1.13'
cache:
  directories:
  - "$HOME/gopath/pkg/mod"
env:
  global:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - GOBUILD="linux-amd64 darwin-amd64"
script:
- "./gofmtcheck.sh"
- make test
- make -j build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XtqF4FkWzHK6UuSvIvPHVwOTswQTVOnEEQdjz9G8daGmaljr94xxVirsKkMLFGCwNDxSMIXAuXGgiOcTkA1csCoygcz1B4zO2gj1Dgp2eYH6FxYGcPUyDdfnGghlJT0HRJK6jgENWIZ/TcR2R7mFXuf7e+4bgbMV6j50YKBcYpr9Q1j0LZH7CCqR8v1WVJIFBJg40jEulW2NnF4OMGVfKACTHCucFLRvbmFQ3PRnR+3i4q0Dn6zAbi5VHX0juFfk4PdhB870CFDByNj1Wz+54erumQyuRH3TDTe0Y7DxASwWqlpgAe/eZsUniuu284+P60Lmb3cOtlv0p/vGn1ouVOenhH6fj589srPrzGjbHs0Pnwcu7l9WSj88pFtdTmntAjEU/rzwvJZiNH6c4ycOiumrp1qozOTGLmJ6H1rXXJiyMUbMTZxFUXnX87yFAOhpJ3cffGPcYjM58rNSAr1mIaDWNTtQuda2wtN1opTayryRKxmNr+11Qk6DXQX5mPjcZLtw8otZkE4FjPoda+09GXPf3vAXszY+bPoDCAnTAwh5yXerW/QC11MqoCQJLWPef+uc6N0PQzHeRTOVoIK7BWLrOR8qY4wir8kQWfJq6NCwM8uKq8EDKAfq3J0w6W5mHO27YiH2KtesAUxVGYOaZ+IKBY6br3KUxbVhddC0pI4=
  file_glob: true
  file: build/*
  on:
    repo: seatgeek/resec
    branch: master
    tags: true