#!/bin/bash

if [ $DOCKER_TAG == "latest" ]
then
  docker build . --build-arg RESEC_VERSION=${SOURCE_BRANCH} -t ${IMAGE_NAME}
else
  docker build . --build-arg RESEC_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME}
fi
