version: '3'

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - resec-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"


  consul-resec-1:
    <<: *consul-agent
    hostname: "consul-resec-1"

  redis-resec-1: &redis
    image: redis:alpine
    hostname: "redis-resec-1"
    networks:
      - resec-demo
  
  resec-1: &resec
    image: seatgeek/resec
    hostname: "resec"
    networks:
      - resec-demo
    environment:
      REDIS_ADDR: redis-resec-1:6379
      CONSUL_HTTP_ADDR: http://consul-resec-1:8500
    depends_on:
      - consul-resec-1
      - redis-resec-1

  consul-resec-2:
    <<: *consul-agent
    hostname: "consul-resec-2"
  redis-resec-2:
    <<: *redis 
    hostname: "redis-resec-2"
  resec-2:
    <<: *resec
    environment:
      REDIS_ADDR: redis-resec-2:6379
      CONSUL_HTTP_ADDR: http://consul-resec-2:8500
    depends_on:
      - consul-resec-2
      - redis-resec-2

  consul-resec-3:
    <<: *consul-agent
    hostname: "consul-resec-3"
  redis-resec-3:
    <<: *redis 
    hostname: "redis-resec-3"
  resec-3:
    <<: *resec
    environment:
      REDIS_ADDR: redis-resec-3:6379
      CONSUL_HTTP_ADDR: http://consul-resec-3:8500
    depends_on:
      - consul-resec-3
      - redis-resec-3



networks:
  resec-demo: